<?xml version="1.0" encoding="UTF-8"?>
<%@ page contentType="text/html" %>
<%@ page pageEncoding="utf-8" %>
<%@ taglib prefix="c"      uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt"    uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Archive Access Control Admin</title>
  <link rel="stylesheet" type="text/css" href="<c:url value="/css/admin.css"/>" />
  
  <style type="text/css">@import url(<c:url value="/jscalendar-1.0/calendar-win2k-1.css"/>);</style>
  <script type="text/javascript" src="<c:url value="/jscalendar-1.0/calendar.js"/>"></script>
  <script type="text/javascript" src="<c:url value="/jscalendar-1.0/lang/calendar-en.js"/>"></script>
  <script type="text/javascript" src="<c:url value="/jscalendar-1.0/calendar-setup.js"/>"></script>
  <script type="text/javascript" src="<c:url value="/js/calendar.js"/>"></script>

</head>
<body>
  <h1>Archive Access Control</h1>