#%RAML 1.0
title: CDX-Server
version: 1.0 (Proposal)
description: |
  The CDX Server is a standalone server that serves the index which Open Wayback uses to lookup captures.
  The index format returned by the CDX Server is known as [CDX](http://iipc.github.io/warc-specifications/specifications/cdx-format/cdx-2015/).
  The CDX Server can alternatively return captures in a line oriented json format called [cdxj](https://github.com/oduwsdl/ORS/wiki/CDXJ).
protocols:
  - HTTP
baseUri: http://cdxserver.example.com/cdx

types:
  CdxLine:
    type: string

  CdxObject:
    type: object
    properties:
      urlkey?: string
      timestamp?: string
      original?: string
      mimetype?: string
      statuscode?: integer
      digest?: string
      redirect?: string
      robotflags?: string
      length?: integer
      offset?: integer
      filename?: string

  CdxList:
    type: object
    description: A list of CdxLines
    properties:
      cdx: CdxObject[]
      resumptionUrl?: string

traits:
  DateRange:
    queryParameters:
      from:
        description: |
          Restrict to only return captures with a timestamp equal to or greater than the submitted *timestamp*.
          * *timestamp* format is: `YYYYMMDDhhmmss`
          * *Timestamp* is expected to be UTC
          * *Timestamp* might have fewer than 14 digits and will then be treated as
          if the missing numbers are zeroes
        displayName: from=<timestamp>
        type: string
        minLength: 0
        maxLength: 14
        pattern: \d{0,14}
        example: 20160214
      to:
        description: |
          Restrict to only return captures with a timestamp smaller than the submitted *timestamp*.
          * *timestamp* format is: `YYYYMMDDhhmmss`
          * *Timestamp* is expected to be UTC
          * *Timestamp* might have fewer than 14 digits and will then be treated as
          if the missing numbers are zeroes
        displayName: to=<timestamp>
        type: string
        minLength: 0
        maxLength: 14
        pattern: \d{0,14}
        example: 20160214132400

  Limit:
    queryParameters:
      limit:
        description: |
          Limit the maximum captures returned in the response.
          If the returned list of captures is cut off by the limit parameter or
          by a server side configured maximum limit, a resumption url will be
          included in the result. This url could be used to resume the search
          from the next result.
          The resumption url will be included only if the query has more results.
        displayName: limit
        type: integer

  Fields:
    queryParameters:
      fields:
        description: |
          Comma separated list of fields to return.

          Allowed fieldnames are:
          * **urlkey** - A normalized version of the uri in *surt* format
          * **timestamp** - A 14 digit timestamp with format `YYYYMMDDhhmmss`
          * **url** - The original url
          * **mime** - The mime type
          * **status** - The response code (for example 200 or 404)
          * **digest** - A checksum of the content of the capture (excluding headers)
          * **length** - The length of the capture in bytes
          * **offset**
          * **filename**
        type: array
        items:
          type: string
        example: original,mimetype

  Collapse:
    queryParameters:
      collapse:
        displayName: collapse=<field>[:<NUM>][,n]
        description: |
          Collapse the result on a field or a substring of a field.

          To use collapsing, add one or more params of the form `collapse=field`
          or `collapse=field:NUM` where `NUM` is the first `NUM` characters of the
          *field* to test.

          Collapsing is done on the complete range of the request. You can collapse
          based on more than one field to restrict this.

          The collapse parameter could also be repeated. Then the second collapse
          parameter is apllied on the result of the former and so on.

          To illustrate this with examples, given the search for `url=example.com/*`
          and the following cdx file (omitting some fields for simplicity):

          ```nohighlight
          com,example)/bar.png 20160215073503 image/png 200 digest1
          com,example)/bar.png 20160215073504 image/png 200 digest1
          com,example)/foo.html 20160215073500 text/html 200 digest2
          com,example)/foo.html 20160215073501 text/html 200 digest3
          com,example)/foo.html 20160215083502 application/json 404 digest4
          com,example)/foo.html 20160215083505 text/html 200 digest2
          com,example)/foo.png 20160215083504 image/png 200 digest5
          ```
          To find out what mime types where captured use `collapse=mime` which will
          return the first line for each mime type:
          ```
          com,example)/bar.png 20160215073503 image/png 200 digest1
          com,example)/foo.html 20160215073500 text/html 200 digest2
          com,example)/foo.html 20160215073502 application/json 404 digest4
          ```
          To reduce the number of captures to only one per hour use: `collapse=timestamp:10`
          (collapsing on the first 10 digits of the timestamp) which will return:
          ```
          com,example)/bar.png 20160215073503 image/png 200 digest1
          com,example)/foo.html 20160215083502 application/json 404 digest4
          ```
          But usually you want this per url: `collapse=urlkey,timestamp:10` which gives:
          ```
          com,example)/bar.png 20160215073503 image/png 200 digest1
          com,example)/foo.html 20160215073500 text/html 200 digest2
          com,example)/foo.html 20160215083502 application/json 404 digest4
          com,example)/foo.png 20160215073504 image/png 200 digest5
          ```

        type: string
        pattern: \w+(:\d+)?(,\w+(:\d+)?)*
        repeat: true

  Filter:
    queryParameters:
      filter:
        displayName: filter=[<modifier>]<field>:<filter>
        description: |
          Filter out captures based on the value of a field.

          The `!` modifier indicates negation.
          The `~` modifier can also be used to specify a regex instead of exact
          filter match. For example: `filter=~mimetype:text/.*` will match any CDX
          line where mime field matches the regex `text/.*`.
          Negation and regex modifier may be combined, eg. `filter=!~mimetype:text/.*`
        type: string
        pattern: |
          [!~]?\w+:.+
        repeat: true

  WildcardUrl:
    queryParameters:
      url:
        type: string
        displayName: url
        description: |
          The url to query. The url is allowed to contain wildcards like this:
          * `www.example.com*` or `www.example.com/*` - All captures for the host
          * `www.example.com/paths/*` - All captures beginning with the specified path
          * `*.example.com` - return all captures for the host and all subdomains
          * With no wildcards the url is matched as it is
        example: www.example.com/paths/*

  Sort:
    queryParameters:
      sort:
        type:
          - string
        displayName: sort
        description: |
          How to sort the result.
          * **asc** - result is returned in increasing lexiographic order
          * **desc** - result is returned in decreasing lexiographic order
        enum:
          - asc
          - desc
        example: desc

  CdxSearchResponse:
    responses:
        200:
          body:
            text/plain:
              type: CdxLine[]
              description: |
                A list of CDX lines in the same format as in the CDX files with two exceptions:
                * There is no format definition
                * There might be a resumption url if there are more lines than the server could serve in one request
              examples:
                NonCompleteResult:
                  displayName: Non complete result
                  description: |
                    This example shows a resultset which was cut off by a limit either
                    caused by the user setting the limit parameter or by a server defined
                    default. Thus the result contains a resumption url which could be used
                    to get more results for this query.
                  strict: false
                  content: !include examples/txt_resumption.txt
                CompleteResult:
                  displayName: Complete result
                  description: |
                    An example of a result with no more captures to get. This could be a
                    complete result or the last request for a result with resumption url.
                  content: !include examples/txt_complete.txt
            application/cdx:
              type: CdxLine[]
              examples:
                NonCompleteResult:
                  displayName: Non complete result
                  description: |
                    This example shows a resultset which was cut off by a limit either
                    caused by the user setting the limit parameter or by a server defined
                    default. Thus the result contains a resumption url which could be used
                    to get more results for this query.
                  strict: false
                  content: !include examples/cdx_resumption.txt
                CompleteResult:
                  displayName: Complete result
                  description: |
                    An example of a result with no more captures to get. This could be a
                    complete result or the last request for a result with resumption url.
                  content: !include examples/cdx_complete.txt
            application/json:
              type: CdxList
              examples:
                NonCompleteResult:
                  displayName: Non complete result
                  description: |
                    This example shows a resultset which was cut off by a limit either
                    caused by the user setting the limit parameter or by a server defined
                    default. Thus the result contains a resumption url which could be used
                    to get more results for this query.
                  content: !include examples/json_resumption.yaml
                CompleteResult:
                  displayName: Complete result
                  description: |
                    An example of a result with no more captures to get. This could be a
                    complete result or the last request for a result with resumption url.
                  content: !include examples/json_complete.yaml
            application/cdxj+ors:
              type: CdxLine[]
              examples:
                NonCompleteResult:
                  displayName: Non complete result
                  description: |
                    This example shows a resultset which was cut off by a limit either
                    caused by the user setting the limit parameter or by a server defined
                    default. Thus the result contains a resumption url which could be used
                    to get more results for this query.
                  content: !include examples/cdxj_resumption.txt
                CompleteResult:
                  displayName: Complete result
                  description: |
                    An example of a result with no more captures to get. This could be a
                    complete result or the last request for a result with resumption url.
                  content: !include examples/cdxj_complete.txt

  CdxGetResponse:
    responses:
        200:
          body:
            text/plain:
              type: CdxLine[]
              description: |
                A list of CDX lines in the same format as in the CDX files with the exception that there is no format definition
              examples:
                DefaultLimit:
                  displayName: Result with default limit
                  description: |
                    An example of a result without setting limit or distance, using
                    the default limit of `1`.
                  content: !include examples/txt_get_one.txt
                DistanceFiveDays:
                  displayName: Query with distance
                  description: |
                    An example of a result with distance set to `distance=432000` (5 days)
                    and `timestamp=20160104010100`.
                  content: !include examples/txt_get_five_days.txt
            application/cdx:
              type: CdxLine[]
              examples:
                DefaultLimit:
                  displayName: Result with default limit
                  description: |
                    An example of a result without setting limit or distance, using
                    the default limit of `1`.
                  content: !include examples/cdx_get_one.txt
                DistanceFiveDays:
                  displayName: Query with distance
                  description: |
                    An example of a result with distance set to `distance=432000` (5 days)
                    and `timestamp=20160104010100`.
                  content: !include examples/cdx_get_five_days.txt
            application/json:
              type: CdxList
              examples:
                DefaultLimit:
                  displayName: Result with default limit
                  description: |
                    An example of a result without setting limit or distance, using
                    the default limit of `1`.
                  content: !include examples/json_get_one.yaml
                DistanceFiveDays:
                  displayName: Query with distance
                  description: |
                    An example of a result with distance set to `distance=432000` (5 days)
                    and `timestamp=20160104010100`.
                  content: !include examples/json_get_five_days.yaml
            application/cdxj+ors:
              type: CdxLine[]
              examples:
                DefaultLimit:
                  displayName: Result with default limit
                  description: |
                    An example of a result without setting limit or distance, using
                    the default limit of `1`.
                  content: !include examples/cdxj_get_one.txt
                DistanceFiveDays:
                  displayName: Query with distance
                  description: |
                    An example of a result with distance set to `distance=432000` (5 days)
                    and `timestamp=20160104010100`.
                  content: !include examples/cdxj_get_five_days.txt


# Resources
/:
  description: List the collections
  get:
    description: |
      The captures are organized in one or more collections. This query lists
      the defined collections for this installation. The other paths of this api
      requires the collection name to be part of the url.
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                name: string
                description: string
            example:
              - name: collection1
                description: Description of collection 1
              - name: collection2
                description: Description of collection 2

/{collection}:
  uriParameters:
    collection:
      type:
        - string
      required: true
      description: Name of the collection to query

  /get:
    description: Request an exact url
    get:
      description: |
        This api is for locating an exact uri closest in time to a reference timestamp.
        The primary usage is to get location information for a resource such as an html file.
        To get embedded resources, submit get requests with the same timestamp as for the primary
        resource.

        A request gets the closest capture(s) for an exact url.
        The result will be sorted closest in time to the submitted timestamp.
        If no timestamp is given, results will be sorted with newest capture first.

        The default is to only return one capture (the closest), but that can be changed
        by using the distance or limit parameters. For performance reasons there might be a
        server side limit to how many captures to return. To get a big number of captures use
        either search or bulk api.
      is:
        - Limit
        - Fields
        - Filter
        - CdxGetResponse
      queryParameters:
        url:
          type: string
          displayName: url
          description: The url to query.
          required: true
        time:
          type: string
          description: |
            Timestamp to get closest capture for.
            * *timestamp* format is: `YYYYMMDDhhmmss`
            * *Timestamp* is expected to be UTC
            * *Timestamp* might have fewer than 14 digits and will then be treated as
            if the missing numbers are zeroes
          minLength: 0
          maxLength: 14
          pattern: \d{0,14}
          example: 20160214132400
        distance:
          type: integer
          displayName: distance
          description: |
            Limit the result to only contain captures with a timestamp no longer than away in seconds
            from the requested timestamp than this number of seconds.
          example: 3600
        limit:
          description:  |
            Limit the maximum captures returned in the response.

            Default value is `1` if neither `limit` nor `distance` parameters are set.
          default: 1
        filter:
          description: |
            Filter out captures based on the value of a field.

            The `!` modifier indicates negation.
            The `~` modifier can also be used to specify a regex instead of exact
            filter match. For example: `filter=~mimetype:text/.*` will match any CDX
            line where mime field matches the regex `text/.*`.
            Negation and regex modifier may be combined, eg. `filter=!~mimetype:text/.*`

            If no filter is given the default is to filter out all captures with status code other than 2xx.
          default: status:~2\d\d
      responses:
        404:
          body:
            application/json:
              type: object
              properties:
                msg:
                  type: string
              example:
                msg: "Not found"

  /search:
    description: Search for captures based on a url or part thereof
    get:
      description: |
        Get a list of captures for a url or a range of urls. This api is for getting enough information
        to build a overview of a part of a collection, for example the calendar view of OpenWayback.

        Different methods exist to filter, collapsing or in other ways limit the number of returned
        results. Filters are always applied before collapsing.
      is:
        - WildcardUrl
        - DateRange
        - Limit
        - Sort
        - Fields
        - Filter
        - Collapse
        - CdxSearchResponse
      queryParameters:
        url:
          required: true

  /bulk:
    description: Request cdx records for consumption by processing tools outside OpenWayback
    is:
      - WildcardUrl
      - DateRange
      - Limit
      - Fields
      - Filter
    get:
      description: |
        The bulk api is optimized for getting big portions of captures for use
        by processing tools like map-reduce. The result is split into batches which
        could be requested in parallel. To allow for high perfomance, the feature
        set of the bulk api is somewhat limited compared to the search and get apis.
        It is for example not possible to do collapsing since that requires to compare
        captures which is not possible when processing different ranges of the captures
        in parallel.

        Using the bulk api is a two step process. First submit a query for the dataset.
        This query won't return any data, but a list of links to batches of data. Then you
        need to submit each of those urls to actually get the data you want.

        All of the parameters allowed for batch requests are added to the initial request,
        but are only influencing the results of the secondary requests which
        gets the actual data. The format of the url for secondary requests are implementation
        specific and altering the secondary requests are not allowed.

        Each batch result is required to be sorted internally, but results from different
        batches might overlap. So if order of the total result is important, then sorting
        must be applied by the client, for example a reduce operation in a map-reduce tool.

        A typical workflow would be:
        1. Submit a search to get a list of pages. *Example: `http://cdxserver.example.com/cdx/main/bulk?url=foo.com&from=2016&limit=1000`*
        2. Sequentially or in paralell use the urls in the result to get each batch of data.
        3. If a page has a resumption url, use the url to get more data from that batch.
      responses:
        200:
          body:
            application/json:
              type: object
              examples:
                InitialRequest:
                  displayName: Initial request
                  description: |
                    Example request for list of batches:
                    `http://cdxserver.example.com/cdx/main/bulk?url=www.example.com*&from=2016&limit=1000`
                  content:
                    count: 2
                    batches:
                      - batch: 1
                        href: http://cdxserver.example.com/cdx/main/bulk?from=www.example.com%2020160101000000&to=www.example.com/somepath%2020160302000000&limit=1000
                      - batch: 2
                        href: http://cdxserver.example.com/cdx/main/bulk?from=www.example.com/somepath%2020160302000000&to=www.example.com/xyz.html%2020160315000000&limit=1000
                FirstBatch:
                  displayName: Requesting the first batch
                  description: |
                    Always use the urls returned by the initial request. The format of urls for each batch
                    is not part of the specification and could differ between installations.

                    Url #1 from batch list: `http://cdxserver.example.com/cdx/main/bulk?from=www.example.com%2020160101000000&to=www.example.com/somepath%2020160302000000&limit=1000`
                  content: !include examples/json_complete.yaml
